//
// Created by hou guoli on 2019/5/7.
//

#ifndef IMAGELIB_CFILETYPE_H
#define IMAGELIB_CFILETYPE_H


enum CFileType {
    CFILE_TYPE_NONE,
    CFILE_TYPE_IMAGE_GIF,
    CFILE_TYPE_IMAGE_XBM,
    CFILE_TYPE_INODE_REG,
    CFILE_TYPE_IMAGE_BMP,
    CFILE_TYPE_IMAGE_EPS,
    CFILE_TYPE_IMAGE_ICO,
    CFILE_TYPE_IMAGE_IFF,
    CFILE_TYPE_IMAGE_JPG,
    CFILE_TYPE_IMAGE_PCX,
    CFILE_TYPE_IMAGE_PNG,
    CFILE_TYPE_IMAGE_PPM,
    CFILE_TYPE_IMAGE_PS,
    CFILE_TYPE_IMAGE_PSP,
    CFILE_TYPE_IMAGE_SGI,
    CFILE_TYPE_IMAGE_SIX,
    CFILE_TYPE_IMAGE_SVG,
    CFILE_TYPE_IMAGE_TGA,
    CFILE_TYPE_IMAGE_TIF,
    CFILE_TYPE_IMAGE_XPM,
    CFILE_TYPE_IMAGE_XWD,
    CFILE_TYPE_IMAGE,
};


#endif //GLFWASSIMP_CFILETYPE_H
