//
// Created by hou guoli on 2019/5/7.
//

#ifndef IMAGELIB_CFILETYPE_H
#define IMAGELIB_CFILETYPE_H


enum CFileType {
    CFILE_TYPE_NONE,
    CFILE_TYPE_IMAGE_GIF,
    CFILE_TYPE_IMAGE_XBM,
    CFILE_TYPE_INODE_REG,
    CFILE_TYPE_IMAGE_BMP,
    CFILE_TYPE_IMAGE_EPS,
    CFILE_TYPE_IMAGE_ICO,
    CFILE_TYPE_IMAGE_IFF,
    CFILE_TYPE_IMAGE_JPG,
    CFILE_TYPE_IMAGE_PCX,
    CFILE_TYPE_IMAGE_PNG,
    CFILE_TYPE_IMAGE_PPM,
    CFILE_TYPE_IMAGE_PS,
    CFILE_TYPE_IMAGE_PSP,
    CFILE_TYPE_IMAGE_SGI,
    CFILE_TYPE_IMAGE_SIX,
    CFILE_TYPE_IMAGE_SVG,
    CFILE_TYPE_IMAGE_TGA,
    CFILE_TYPE_IMAGE_TIF,
    CFILE_TYPE_IMAGE_XPM,
    CFILE_TYPE_IMAGE_XWD,
    CFILE_TYPE_IMAGE,
    CFILE_TYPE_INODE_FIFO,
    CFILE_TYPE_INODE_CHR,
    CFILE_TYPE_INODE_DIR,
    CFILE_TYPE_INODE_BLK,
    CFILE_TYPE_INODE_LNK,
    CFILE_TYPE_INODE_SOCK,
    CFILE_TYPE_TEXT_PLAIN,
    CFILE_TYPE_TEXT_BINARY,
    CFILE_TYPE_TEXT_HTML,
    CFILE_TYPE_TEXT_XML,
    CFILE_TYPE_TEXT_TAR,
    CFILE_TYPE_TEXT_TGZ,
    CFILE_TYPE_TEXT_GZIP,

    CFILE_TYPE_APP_EXEC,
    CFILE_TYPE_APP_CORE,
    CFILE_TYPE_APP_SH,
    CFILE_TYPE_APP_CSH,
    CFILE_TYPE_APP_KSH,
    CFILE_TYPE_APP_TCL,
    CFILE_TYPE_APP_EPS,

    CFILE_TYPE_SOUND_WAV,
};


#endif //GLFWASSIMP_CFILETYPE_H
